# Generated by Django 4.2.6 on 2023-11-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='uid',
            new_name='did',
        ),
    ]
