# Generated by Django 4.2.6 on 2023-11-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0003_rename_uid_instructor_did'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='seating_capacity',
            new_name='numb_cabins_per_room',
        ),
    ]
