# Generated by Django 4.2.6 on 2023-11-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0005_remove_course_max_numb_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='patient_number',
        ),
    ]
