# Generated by Django 4.2.6 on 2023-11-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0006_rename_course_name_course_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructors',
            new_name='doctors',
        ),
    ]
