# Generated by Django 4.2.6 on 2023-11-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0007_rename_instructors_course_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='courses',
            new_name='patients',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='spec_name',
        ),
    ]
