# Generated by Django 4.2.6 on 2023-11-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0008_rename_courses_department_patients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='num_class_in_week',
            new_name='num_appointments_in_week',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='department',
            new_name='specialization',
        ),
    ]
